add support to applications api closes #200
crowdin/crowdin-api-client-java pull request #210
Opened 2023-10-28 08:42 UTC by sugan0tech

2023-10-28 09:06 UTC, sugan0tech commented
@andrii-bodnar made the changes, please provide the necessary changes.

2023-10-30 08:23 UTC, andrii-bodnar requested changes

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * @param applicationIdentifier identifier of the application.
```suggestion
     * @param applicationIdentifier identifier of the application
```

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     */
```suggestion
    /**
     * @param applicationIdentifier identifier of the application
     * @param path The path is implemented by the application
     * @param request request object
     * @return application data
     * @see <ul>
     * <li><a href="https://developer.crowdin.com/api/v2/#operation/api.applications.api.put" target="_blank"><b>API Documentation</b></a></li>
<li><a href="https://developer.crowdin.com/enterprise/api/v2/#operation/api.applications.api.put" target="_blank"><b>Enterprise API Documentation</b></a></li>
     * </ul>
     */
```

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +    public ResponseObject<ApplicationData> updateOrReplaceApplicationData(String applicationIdentifier, String path, UpdateOrReplaceApplicationDataRequest request) throws HttpException, HttpBadReques
`updateOrReplaceApplicationData` -> `updateOrRestoreApplicationData`

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * @param applicationIdentifier identifier of the application.
```suggestion
     * @param applicationIdentifier identifier of the application
```

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * <li><a href="https://developer.crowdin.com/api/v2/#operation/api.applications.api.post" target="_blank"><b>API Documentation</b></a></li>
add "Enterprise API Documentation" link

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * <li><a href="https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.members.delete" target="_blank"><b>Enterprise API Documentation</b></a></li>
Enterprise API Documentation

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * @param applicationIdentifier identifier of the application.
```suggestion
     * @param applicationIdentifier identifier of the application
```

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * @param request request object
```suggestion
     * @param request request object
     * @return application data
```

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * @see <ul>
```suggestion
     * @param applicationIdentifier identifier of the application
     * @param path The path is implemented by the application
     * @param request request object
     * @return application data
     * @see <ul>
```

2023-10-30 08:23 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * <li><a href="https://developer.crowdin.com/api/v2/#operation/api.applications.api.put" target="_blank"><b>API Documentation</b></a></li>
add "Enterprise API Documentation"

2023-10-30 09:43 UTC, andrii-bodnar requested changes

2023-10-30 09:43 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +    public ResponseObject<ApplicationData> updateOrReplaceApplicationData(String applicationIdentifier, String path, UpdateOrRestoreApplicationDataRequest request) throws HttpException, HttpBadReques
updateOr**Restore**ApplicationData

2023-10-30 09:43 UTC, andrii-bodnar commented on src/main/java/com/crowdin/client/applications/ApplicationsApi.java
> +     * @return application data
put return after params

2023-10-30 09:43 UTC, andrii-bodnar commented on src/test/java/com/crowdin/client/applications/ApplicationsApiTest.java
> +    void updateOrReplaceApplicationData() {
updateOr**Restore**ApplicationData

2023-10-30 09:55 UTC, andrii-bodnar approved these changes
@sugan0tech thank you!

2023-10-30 09:56 UTC, merged